Update manual-dispatch.yml

diff --git a/.github/workflows/manual-dispatch.yml b/.github/workflows/manual-dispatch.yml
--- a/.github/workflows/manual-dispatch.yml
+++ b/.github/workflows/manual-dispatch.yml
@@ -30,5 +30,8 @@ jobs:
       - name: Print user message
         run: echo "Message = ${{ github.event.inputs.message }}"
 
-      - name: Final step
-        run: echo "✅ Workflow completed successfully"
+      - name: Force fail pipeline
+        run: |
+          echo "❌ PIPELINE FAILED"
+          exit 1
+``
